### ISSUE TITLE
TOML based configuration

### ISSUE THREAD

**Issue by 256dpi** [shiftr-io/sihl#7]
Use something like this:

```toml
[librato]
user = "hello@example.com"
token = "9uijf9df98df8"

[sentry]
user = "hello@example.com"
token = "76rtzfguz789"

[default]
forwarder = "librato"
logger = "sentry"

[mongodb]
uri = "mongodb://0.0.0.0:271017"
```
